name: "Deploy Codigo test"

on:
  push:
    branches: ["main"]

jobs:
  test-actions:
    runs-on: ubuntu-latest

    steps:
      - name: "Hello world"
        run: echo "Correr migraciones"
      - name: "dime la fecha"
        run: date
      - name: Muestra el contenido del directorio
        run: ls -la
